// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kcH3B1wZpZT0HPE738f_FtQAvoZLE68',
    appId: '1:702596531582:web:c71ee15c9d58951cb3df2f',
    messagingSenderId: '702596531582',
    projectId: 'transporte-app-246b0',
    authDomain: 'transporte-app-246b0.firebaseapp.com',
    storageBucket: 'transporte-app-246b0.appspot.com',
    measurementId: 'G-NXFY84K88Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxe1Cmd2AnlO8SIEQt12IXt_G8DZ2xegg',
    appId: '1:702596531582:android:1b9c54b5598429cab3df2f',
    messagingSenderId: '702596531582',
    projectId: 'transporte-app-246b0',
    storageBucket: 'transporte-app-246b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYq5shx4CCSDGlnoHlbFQYDSGx4PT5hKk',
    appId: '1:702596531582:ios:34739c40b42d1330b3df2f',
    messagingSenderId: '702596531582',
    projectId: 'transporte-app-246b0',
    storageBucket: 'transporte-app-246b0.appspot.com',
    iosClientId: '702596531582-ls80haoa449l256ta2qjrlnnr2cjorf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.transporteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYq5shx4CCSDGlnoHlbFQYDSGx4PT5hKk',
    appId: '1:702596531582:ios:34739c40b42d1330b3df2f',
    messagingSenderId: '702596531582',
    projectId: 'transporte-app-246b0',
    storageBucket: 'transporte-app-246b0.appspot.com',
    iosClientId: '702596531582-ls80haoa449l256ta2qjrlnnr2cjorf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.transporteApp',
  );
}
